# 운영 환경 설정
spring:
  data:
    redis:
      host: ${REDIS_HOST:redis-cluster.example.com}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: true
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5

# State Machine - Redis 사용
security:
  statemachine:
    redis:
      enabled: true  # 운영 환경에서는 Redis 사용
      ttl-minutes: 60

logging:
  level:
    io.springsecurity.springsecurity6x: INFO
    org.springframework.statemachine: WARN