# 개발 환경 설정
spring:
  data:
    redis:
      host: localhost
      port: 6379

# State Machine - In-Memory 사용
security:
  statemachine:
    redis:
      enabled: false  # 개발 환경에서는 In-Memory 사용

logging:
  level:
    io.springsecurity.springsecurity6x: DEBUG
    org.springframework.statemachine: DEBUG